apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx

spec:
  replicas: 5

  selector:
    matchLabels:
      app: my-nginx

  template:
    metadata:
      labels:
        app: my-nginx

    spec:
      nodeSelector:
        kubernetes.io/hostname: node01

      containers:
        - name: nginx
          image: my-nginx:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

      volumes:
        - name: nginx-html
          configMap:
            name: my-nginx-config